const SET_USERS = 'SET_USERS';
const SET_LOADING = 'SET_LOADING';
const DESTROY_USER = 'DESTROY_USER';
const UPDATE_USER = 'UPDATE_USER';
const CREATE_USER = 'CREATE_USER';
const SET_ERROR = 'SET_ERROR';

export {
  SET_USERS,
  SET_LOADING,
  SET_ERROR,
  DESTROY_USER,
  UPDATE_USER,
  CREATE_USER
};
